/* Generated by Yosys 0.57+88 (git sha1 fe9eed049, clang++ 18.1.8 -fPIC -O3) */

(* top =  1  *)
(* src = "/home/navneet/Documents/Verilog/sky130RTLDesignAndSynthesisWorkshop/verilog_files/multiple_modules.v:10.1-14.10" *)
module multiple_modules(a, b, c, y);
  (* src = "/home/navneet/Documents/Verilog/sky130RTLDesignAndSynthesisWorkshop/verilog_files/multiple_modules.v:10.32-10.33" *)
  input a;
  wire a;
  (* src = "/home/navneet/Documents/Verilog/sky130RTLDesignAndSynthesisWorkshop/verilog_files/multiple_modules.v:10.41-10.42" *)
  input b;
  wire b;
  (* src = "/home/navneet/Documents/Verilog/sky130RTLDesignAndSynthesisWorkshop/verilog_files/multiple_modules.v:10.50-10.51" *)
  input c;
  wire c;
  (* src = "/home/navneet/Documents/Verilog/sky130RTLDesignAndSynthesisWorkshop/verilog_files/multiple_modules.v:10.61-10.62" *)
  output y;
  wire y;
  (* src = "/home/navneet/Documents/Verilog/sky130RTLDesignAndSynthesisWorkshop/verilog_files/multiple_modules.v:11.7-11.11" *)
  wire net1;
  (* module_not_derived = 32'd1 *)
  (* src = "/home/navneet/Documents/Verilog/sky130RTLDesignAndSynthesisWorkshop/verilog_files/multiple_modules.v:12.14-12.38" *)
  sub_module1 u1 (
    .a(a),
    .b(b),
    .y(net1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/navneet/Documents/Verilog/sky130RTLDesignAndSynthesisWorkshop/verilog_files/multiple_modules.v:13.14-13.38" *)
  sub_module2 u2 (
    .a(net1),
    .b(c),
    .y(y)
  );
endmodule

(* src = "/home/navneet/Documents/Verilog/sky130RTLDesignAndSynthesisWorkshop/verilog_files/multiple_modules.v:5.1-7.10" *)
module sub_module1(a, b, y);
  (* src = "/home/navneet/Documents/Verilog/sky130RTLDesignAndSynthesisWorkshop/verilog_files/multiple_modules.v:5.27-5.28" *)
  input a;
  wire a;
  (* src = "/home/navneet/Documents/Verilog/sky130RTLDesignAndSynthesisWorkshop/verilog_files/multiple_modules.v:5.36-5.37" *)
  input b;
  wire b;
  (* src = "/home/navneet/Documents/Verilog/sky130RTLDesignAndSynthesisWorkshop/verilog_files/multiple_modules.v:5.46-5.47" *)
  output y;
  wire y;
  assign y = b & a;
endmodule

(* src = "/home/navneet/Documents/Verilog/sky130RTLDesignAndSynthesisWorkshop/verilog_files/multiple_modules.v:1.1-3.10" *)
module sub_module2(a, b, y);
  (* src = "/home/navneet/Documents/Verilog/sky130RTLDesignAndSynthesisWorkshop/verilog_files/multiple_modules.v:1.27-1.28" *)
  input a;
  wire a;
  (* src = "/home/navneet/Documents/Verilog/sky130RTLDesignAndSynthesisWorkshop/verilog_files/multiple_modules.v:1.36-1.37" *)
  input b;
  wire b;
  (* src = "/home/navneet/Documents/Verilog/sky130RTLDesignAndSynthesisWorkshop/verilog_files/multiple_modules.v:1.46-1.47" *)
  output y;
  wire y;
  assign y = b | a;
endmodule
