/* Generated by Yosys 0.57+88 (git sha1 fe9eed049, clang++ 18.1.8 -fPIC -O3) */

(* top =  1  *)
(* src = "/home/navneet/Documents/Verilog/sky130RTLDesignAndSynthesisWorkshop/verilog_files/bad_case.v:1.1-13.10" *)
module bad_case(i0, i1, i2, i3, sel, y);
  (* src = "/home/navneet/Documents/Verilog/sky130RTLDesignAndSynthesisWorkshop/verilog_files/bad_case.v:1.24-1.26" *)
  input i0;
  wire i0;
  (* src = "/home/navneet/Documents/Verilog/sky130RTLDesignAndSynthesisWorkshop/verilog_files/bad_case.v:1.35-1.37" *)
  input i1;
  wire i1;
  (* src = "/home/navneet/Documents/Verilog/sky130RTLDesignAndSynthesisWorkshop/verilog_files/bad_case.v:1.45-1.47" *)
  input i2;
  wire i2;
  (* src = "/home/navneet/Documents/Verilog/sky130RTLDesignAndSynthesisWorkshop/verilog_files/bad_case.v:1.55-1.57" *)
  input i3;
  wire i3;
  (* src = "/home/navneet/Documents/Verilog/sky130RTLDesignAndSynthesisWorkshop/verilog_files/bad_case.v:1.72-1.75" *)
  input [1:0] sel;
  wire [1:0] sel;
  (* src = "/home/navneet/Documents/Verilog/sky130RTLDesignAndSynthesisWorkshop/verilog_files/bad_case.v:1.88-1.89" *)
  output y;
  wire y;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  (* src = "/home/navneet/Documents/Verilog/sky130RTLDesignAndSynthesisWorkshop/verilog_files/bad_case.v:1.24-1.26" *)
  wire _09_;
  (* src = "/home/navneet/Documents/Verilog/sky130RTLDesignAndSynthesisWorkshop/verilog_files/bad_case.v:1.35-1.37" *)
  wire _10_;
  (* src = "/home/navneet/Documents/Verilog/sky130RTLDesignAndSynthesisWorkshop/verilog_files/bad_case.v:1.45-1.47" *)
  wire _11_;
  (* src = "/home/navneet/Documents/Verilog/sky130RTLDesignAndSynthesisWorkshop/verilog_files/bad_case.v:1.55-1.57" *)
  wire _12_;
  (* src = "/home/navneet/Documents/Verilog/sky130RTLDesignAndSynthesisWorkshop/verilog_files/bad_case.v:1.72-1.75" *)
  wire _13_;
  (* src = "/home/navneet/Documents/Verilog/sky130RTLDesignAndSynthesisWorkshop/verilog_files/bad_case.v:1.72-1.75" *)
  wire _14_;
  (* src = "/home/navneet/Documents/Verilog/sky130RTLDesignAndSynthesisWorkshop/verilog_files/bad_case.v:1.88-1.89" *)
  wire _15_;
  sky130_fd_sc_hd__mux4_2 _16_ (
    .A0(_09_),
    .A1(_10_),
    .A2(_11_),
    .A3(_12_),
    .S0(_13_),
    .S1(_14_),
    .X(_15_)
  );
  assign _13_ = sel[0];
  assign _14_ = sel[1];
  assign _11_ = i2;
  assign _10_ = i1;
  assign _09_ = i0;
  assign _12_ = i3;
  assign y = _15_;
endmodule
